
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package my.code.jax.ws.departmentService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-17T14:55:42.678+08:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "DepartmentServiceAgentService",
                      portName = "DepartmentService",
                      targetNamespace = "www.cattsoft.com",
                      wsdlLocation = "./WEB-INF/wsdl/DepartmentService.xml",
                      endpointInterface = "my.code.jax.ws.departmentService.DepartmentServiceAgent")
                      
public class DepartmentServiceAgentImpl implements DepartmentServiceAgent {

    private static final Logger LOG = Logger.getLogger(DepartmentServiceAgentImpl.class.getName());

    /* (non-Javadoc)
     * @see my.code.jax.ws.departmentService.DepartmentServiceAgent#deleteDepartment(java.lang.String  deptXML )*
     */
    public java.lang.String deleteDepartment(java.lang.String deptXML) { 
        LOG.info("Executing operation deleteDepartment");
        System.out.println(deptXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see my.code.jax.ws.departmentService.DepartmentServiceAgent#addDepartment(java.lang.String  deptXML )*
     */
    public java.lang.String addDepartment(java.lang.String deptXML) { 
        LOG.info("Executing operation addDepartment");
        System.out.println(deptXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see my.code.jax.ws.departmentService.DepartmentServiceAgent#updateDepartment(java.lang.String  deptXML )*
     */
    public java.lang.String updateDepartment(java.lang.String deptXML) { 
        LOG.info("Executing operation updateDepartment");
        System.out.println(deptXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
