package my.code.jax.ws.DepartmentService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-14T11:20:15.431+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "www.cattsoft.com", name = "DepartmentServiceAgent")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DepartmentServiceAgent {

    @WebResult(name = "deleteDepartmentReturn", targetNamespace = "www.cattsoft.com", partName = "deleteDepartmentReturn")
    @WebMethod
    public java.lang.String deleteDepartment(
        @WebParam(partName = "deptXML", name = "deptXML")
        java.lang.String deptXML
    );

    @WebResult(name = "addDepartmentReturn", targetNamespace = "www.cattsoft.com", partName = "addDepartmentReturn")
    @WebMethod
    public java.lang.String addDepartment(
        @WebParam(partName = "deptXML", name = "deptXML")
        java.lang.String deptXML
    );

    @WebResult(name = "updateDepartmentReturn", targetNamespace = "www.cattsoft.com", partName = "updateDepartmentReturn")
    @WebMethod
    public java.lang.String updateDepartment(
        @WebParam(partName = "deptXML", name = "deptXML")
        java.lang.String deptXML
    );
}
