
package my.code.jax.ws.DepartmentService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-14T11:20:15.403+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class DepartmentServiceAgent_DepartmentService_Client {

    private static final QName SERVICE_NAME = new QName("www.cattsoft.com", "DepartmentServiceAgentService");

    private DepartmentServiceAgent_DepartmentService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DepartmentServiceAgentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DepartmentServiceAgentService ss = new DepartmentServiceAgentService(wsdlURL, SERVICE_NAME);
        DepartmentServiceAgent port = ss.getDepartmentService();  
        
        {
        System.out.println("Invoking deleteDepartment...");
        java.lang.String _deleteDepartment_deptXML = "";
        java.lang.String _deleteDepartment__return = port.deleteDepartment(_deleteDepartment_deptXML);
        System.out.println("deleteDepartment.result=" + _deleteDepartment__return);


        }
        {
        System.out.println("Invoking addDepartment...");
        java.lang.String _addDepartment_deptXML = "";
        java.lang.String _addDepartment__return = port.addDepartment(_addDepartment_deptXML);
        System.out.println("addDepartment.result=" + _addDepartment__return);


        }
        {
        System.out.println("Invoking updateDepartment...");
        java.lang.String _updateDepartment_deptXML = "";
        java.lang.String _updateDepartment__return = port.updateDepartment(_updateDepartment_deptXML);
        System.out.println("updateDepartment.result=" + _updateDepartment__return);


        }

        System.exit(0);
    }

}
