
package my.code.jax.ws.UserService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-14T11:14:02.799+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class UserServiceAgent_UserService_Client {

    private static final QName SERVICE_NAME = new QName("www.cattsoft.com", "UserServiceAgentService");

    private UserServiceAgent_UserService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserServiceAgentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserServiceAgentService ss = new UserServiceAgentService(wsdlURL, SERVICE_NAME);
        UserServiceAgent port = ss.getUserService();  
        
        {
        System.out.println("Invoking deletePerson...");
        java.lang.String _deletePerson_personXML = "";
        java.lang.String _deletePerson__return = port.deletePerson(_deletePerson_personXML);
        System.out.println("deletePerson.result=" + _deletePerson__return);


        }
        {
        System.out.println("Invoking updatePerson...");
        java.lang.String _updatePerson_personXML = "";
        java.lang.String _updatePerson__return = port.updatePerson(_updatePerson_personXML);
        System.out.println("updatePerson.result=" + _updatePerson__return);


        }
        {
        System.out.println("Invoking addPerson...");
        java.lang.String _addPerson_personXML = "";
        java.lang.String _addPerson__return = port.addPerson(_addPerson_personXML);
        System.out.println("addPerson.result=" + _addPerson__return);


        }

        System.exit(0);
    }

}
