package my.code.jax.ws.roleService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-17T14:56:28.378+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "www.cattsoft.com", name = "RoleServiceAgent")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RoleServiceAgent {

    @WebResult(name = "updateRoleReturn", targetNamespace = "www.cattsoft.com", partName = "updateRoleReturn")
    @WebMethod
    public java.lang.String updateRole(
        @WebParam(partName = "roleXML", name = "roleXML")
        java.lang.String roleXML
    );

    @WebResult(name = "addUserRoleSetReturn", targetNamespace = "www.cattsoft.com", partName = "addUserRoleSetReturn")
    @WebMethod
    public java.lang.String addUserRoleSet(
        @WebParam(partName = "userRoleXML", name = "userRoleXML")
        java.lang.String userRoleXML
    );

    @WebResult(name = "deleteUserRoleSetReturn", targetNamespace = "www.cattsoft.com", partName = "deleteUserRoleSetReturn")
    @WebMethod
    public java.lang.String deleteUserRoleSet(
        @WebParam(partName = "userRoleXML", name = "userRoleXML")
        java.lang.String userRoleXML
    );

    @WebResult(name = "deleteRoleReturn", targetNamespace = "www.cattsoft.com", partName = "deleteRoleReturn")
    @WebMethod
    public java.lang.String deleteRole(
        @WebParam(partName = "roleXML", name = "roleXML")
        java.lang.String roleXML
    );

    @WebResult(name = "addRoleReturn", targetNamespace = "www.cattsoft.com", partName = "addRoleReturn")
    @WebMethod
    public java.lang.String addRole(
        @WebParam(partName = "roleXML", name = "roleXML")
        java.lang.String roleXML
    );
}
