
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package my.code.jax.ws.RoleService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-14T11:19:17.129+08:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "RoleServiceAgentService",
                      portName = "RoleService",
                      targetNamespace = "www.cattsoft.com",
                      wsdlLocation = "RoleService.xml",
                      endpointInterface = "my.code.jax.ws.RoleService.RoleServiceAgent")
                      
public class RoleServiceAgentImpl implements RoleServiceAgent {

    private static final Logger LOG = Logger.getLogger(RoleServiceAgentImpl.class.getName());

    /* (non-Javadoc)
     * @see my.code.jax.ws.RoleService.RoleServiceAgent#updateRole(java.lang.String  roleXML )*
     */
    public java.lang.String updateRole(java.lang.String roleXML) { 
        LOG.info("Executing operation updateRole");
        System.out.println(roleXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see my.code.jax.ws.RoleService.RoleServiceAgent#addUserRoleSet(java.lang.String  userRoleXML )*
     */
    public java.lang.String addUserRoleSet(java.lang.String userRoleXML) { 
        LOG.info("Executing operation addUserRoleSet");
        System.out.println(userRoleXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see my.code.jax.ws.RoleService.RoleServiceAgent#deleteUserRoleSet(java.lang.String  userRoleXML )*
     */
    public java.lang.String deleteUserRoleSet(java.lang.String userRoleXML) { 
        LOG.info("Executing operation deleteUserRoleSet");
        System.out.println(userRoleXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see my.code.jax.ws.RoleService.RoleServiceAgent#deleteRole(java.lang.String  roleXML )*
     */
    public java.lang.String deleteRole(java.lang.String roleXML) { 
        LOG.info("Executing operation deleteRole");
        System.out.println(roleXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see my.code.jax.ws.RoleService.RoleServiceAgent#addRole(java.lang.String  roleXML )*
     */
    public java.lang.String addRole(java.lang.String roleXML) { 
        LOG.info("Executing operation addRole");
        System.out.println(roleXML);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
